' DRAW - Live WIP BAS Stream
' Regenerated whenever history is cleared. New records append below.
' Source project generated by DRAW 0.16.0
' Tail this file while drawing to watch emitted BASIC.

OPTION _EXPLICIT

CONST CANVAS_W = 864
CONST CANVAS_H = 486
CONST MAX_LAYER_ID = 64
DIM SHARED layerImg(1 TO MAX_LAYER_ID) AS LONG

SCREEN _NEWIMAGE(CANVAS_W, CANVAS_H, 32)
CLS , _RGB32(255, 0, 255)
InitWipLayers

SUB InitWipLayers ()
    DIM i AS INTEGER
    FOR i = 1 TO MAX_LAYER_ID
        layerImg(i) = _NEWIMAGE(CANVAS_W, CANVAS_H, 32)
        IF layerImg(i) < -1 THEN
            _DEST layerImg(i)
            CLS , _RGBA32(0, 0, 0, 0)
        END IF
    NEXT i
    _DEST 0
END SUB

SUB FloodFillLikeDRAW (layerId AS LONG, startX AS INTEGER, startY AS INTEGER, fillCol AS _UNSIGNED LONG)
    DIM targetCol AS _UNSIGNED LONG
    DIM stackTop AS LONG
    DIM currentX AS INTEGER, currentY AS INTEGER
    DIM leftX AS INTEGER, rightX AS INTEGER, scanX AS INTEGER
    DIM stackX() AS INTEGER, stackY() AS INTEGER
    IF layerId < 1 OR layerId > MAX_LAYER_ID THEN EXIT SUB
    IF layerImg(layerId) >= -1 THEN EXIT SUB
    IF startX < 0 OR startY < 0 OR startX >= CANVAS_W OR startY >= CANVAS_H THEN EXIT SUB
    _DEST layerImg(layerId)
    targetCol = POINT(startX, startY)
    IF targetCol = fillCol THEN _DEST 0: EXIT SUB
    REDIM stackX(0 TO CANVAS_W * CANVAS_H - 1) AS INTEGER
    REDIM stackY(0 TO CANVAS_W * CANVAS_H - 1) AS INTEGER
    stackTop = 0
    stackX(stackTop) = startX: stackY(stackTop) = startY
    DO WHILE stackTop >= 0
        currentX = stackX(stackTop): currentY = stackY(stackTop)
        stackTop = stackTop - 1
        IF POINT(currentX, currentY) <> targetCol THEN _CONTINUE
        leftX = currentX
        DO WHILE leftX > 0 AND POINT(leftX - 1, currentY) = targetCol
            leftX = leftX - 1
        LOOP
        rightX = currentX
        DO WHILE rightX < CANVAS_W - 1 AND POINT(rightX + 1, currentY) = targetCol
            rightX = rightX + 1
        LOOP
        LINE (leftX, currentY)-(rightX, currentY), fillCol
        IF currentY > 0 THEN
            scanX = leftX
            DO WHILE scanX <= rightX
                DO WHILE scanX <= rightX AND POINT(scanX, currentY - 1) <> targetCol
                    scanX = scanX + 1
                LOOP
                IF scanX <= rightX THEN
                    stackTop = stackTop + 1
                    stackX(stackTop) = scanX: stackY(stackTop) = currentY - 1
                    DO WHILE scanX <= rightX AND POINT(scanX, currentY - 1) = targetCol
                        scanX = scanX + 1
                    LOOP
                END IF
            LOOP
        END IF
        IF currentY < CANVAS_H - 1 THEN
            scanX = leftX
            DO WHILE scanX <= rightX
                DO WHILE scanX <= rightX AND POINT(scanX, currentY + 1) <> targetCol
                    scanX = scanX + 1
                LOOP
                IF scanX <= rightX THEN
                    stackTop = stackTop + 1
                    stackX(stackTop) = scanX: stackY(stackTop) = currentY + 1
                    DO WHILE scanX <= rightX AND POINT(scanX, currentY + 1) = targetCol
                        scanX = scanX + 1
                    LOOP
                END IF
            LOOP
        END IF
    LOOP
    _DEST 0
END SUB

' --- appended drawing ops ---
