' DRAW - Generated BAS History Export
' Source project generated by DRAW 0.16.0
' Canvas: 864x486
' History records: 9 (current cursor=9)
' Supported records in this export: 9
' Expanded BASIC records in this export: 2
' Unsupported records omitted from executable replay: 0

OPTION _EXPLICIT

CONST CANVAS_W = 864
CONST CANVAS_H = 486
CONST MAX_LAYER_ID = 1
DIM SHARED layerImg(1 TO MAX_LAYER_ID) AS LONG
DIM SHARED layerActive(1 TO MAX_LAYER_ID) AS INTEGER
DIM SHARED layerVisible(1 TO MAX_LAYER_ID) AS INTEGER
DIM SHARED layerZ(1 TO MAX_LAYER_ID) AS INTEGER
DIM SHARED layerOpacity(1 TO MAX_LAYER_ID) AS INTEGER
DIM SHARED layerName(1 TO MAX_LAYER_ID) AS STRING * 64

SCREEN _NEWIMAGE(CANVAS_W, CANVAS_H, 32)
CLS , _RGBA32(0, 0, 0, 0)
ReplayHistory
RenderLayers
_DISPLAY
SLEEP
SYSTEM

SUB CreateLayer (layerId AS LONG, zPos AS INTEGER, isVisible AS INTEGER, opacityVal AS INTEGER, layerLabel AS STRING)
    IF layerId < 1 OR layerId > MAX_LAYER_ID THEN EXIT SUB
    IF layerImg(layerId) < -1 THEN _FREEIMAGE layerImg(layerId)
    layerImg(layerId) = _NEWIMAGE(CANVAS_W, CANVAS_H, 32)
    IF layerImg(layerId) >= -1 THEN EXIT SUB
    _DEST layerImg(layerId)
    CLS , _RGBA32(0, 0, 0, 0)
    _DEST 0
    layerActive(layerId) = -1
    layerVisible(layerId) = isVisible
    layerZ(layerId) = zPos
    layerOpacity(layerId) = opacityVal
    layerName(layerId) = layerLabel
END SUB

SUB DeleteLayer (layerId AS LONG)
    IF layerId < 1 OR layerId > MAX_LAYER_ID THEN EXIT SUB
    IF layerImg(layerId) < -1 THEN _FREEIMAGE layerImg(layerId): layerImg(layerId) = 0
    layerActive(layerId) = 0
    layerVisible(layerId) = 0
    layerZ(layerId) = 0
    layerOpacity(layerId) = 0
    layerName(layerId) = ""
END SUB

SUB MoveLayerToZ (layerId AS LONG, targetZ AS INTEGER)
    DIM currentZ AS INTEGER
    DIM i AS INTEGER
    IF layerId < 1 OR layerId > MAX_LAYER_ID THEN EXIT SUB
    IF layerActive(layerId) = 0 THEN EXIT SUB
    currentZ = layerZ(layerId)
    IF currentZ = targetZ THEN EXIT SUB
    IF targetZ > currentZ THEN
        FOR i = 1 TO MAX_LAYER_ID
            IF i <> layerId AND layerActive(i) AND layerZ(i) > currentZ AND layerZ(i) <= targetZ THEN layerZ(i) = layerZ(i) - 1
        NEXT i
    ELSE
        FOR i = 1 TO MAX_LAYER_ID
            IF i <> layerId AND layerActive(i) AND layerZ(i) >= targetZ AND layerZ(i) < currentZ THEN layerZ(i) = layerZ(i) + 1
        NEXT i
    END IF
    layerZ(layerId) = targetZ
END SUB

SUB DrawFilledEllipse (x1 AS INTEGER, y1 AS INTEGER, x2 AS INTEGER, y2 AS INTEGER, drawCol AS _UNSIGNED LONG, layerId AS LONG)
    DIM cx AS INTEGER, cy AS INTEGER
    DIM rx AS SINGLE, ry AS SINGLE
    DIM y AS INTEGER, xLeft AS INTEGER, xRight AS INTEGER, scanX AS INTEGER
    DIM dy AS SINGLE, dx AS SINGLE
    IF layerId < 1 OR layerId > MAX_LAYER_ID THEN EXIT SUB
    IF layerImg(layerId) >= -1 THEN EXIT SUB
    cx = (x1 + x2) \ 2: cy = (y1 + y2) \ 2
    rx = ABS(x2 - x1) / 2: ry = ABS(y2 - y1) / 2
    IF rx <= 0 OR ry <= 0 THEN EXIT SUB
    _DEST layerImg(layerId)
    FOR y = cy - INT(ry + 0.5) TO cy + INT(ry + 0.5)
        dy = (y - cy) / ry
        IF ABS(dy) <= 1.0001 THEN
            dx = rx * SQR(1 - dy * dy)
            xLeft = cx - INT(dx + 0.5)
            xRight = cx + INT(dx + 0.5)
            IF xLeft <= xRight THEN LINE (xLeft, y)-(xRight, y), drawCol
        END IF
    NEXT y
    _DEST 0
END SUB

SUB FloodFillLikeDRAW (layerId AS LONG, startX AS INTEGER, startY AS INTEGER, fillCol AS _UNSIGNED LONG)
    DIM targetCol AS _UNSIGNED LONG
    DIM stackTop AS LONG
    DIM currentX AS INTEGER, currentY AS INTEGER
    DIM leftX AS INTEGER, rightX AS INTEGER, scanX AS INTEGER
    DIM stackX() AS INTEGER, stackY() AS INTEGER
    IF layerId < 1 OR layerId > MAX_LAYER_ID THEN EXIT SUB
    IF layerImg(layerId) >= -1 THEN EXIT SUB
    IF startX < 0 OR startY < 0 OR startX >= CANVAS_W OR startY >= CANVAS_H THEN EXIT SUB
    _DEST layerImg(layerId)
    targetCol = POINT(startX, startY)
    IF targetCol = fillCol THEN _DEST 0: EXIT SUB
    REDIM stackX(0 TO CANVAS_W * CANVAS_H - 1) AS INTEGER
    REDIM stackY(0 TO CANVAS_W * CANVAS_H - 1) AS INTEGER
    stackTop = 0
    stackX(stackTop) = startX: stackY(stackTop) = startY
    DO WHILE stackTop >= 0
        currentX = stackX(stackTop): currentY = stackY(stackTop)
        stackTop = stackTop - 1
        IF POINT(currentX, currentY) <> targetCol THEN _CONTINUE
        leftX = currentX
        DO WHILE leftX > 0 AND POINT(leftX - 1, currentY) = targetCol
            leftX = leftX - 1
        LOOP
        rightX = currentX
        DO WHILE rightX < CANVAS_W - 1 AND POINT(rightX + 1, currentY) = targetCol
            rightX = rightX + 1
        LOOP
        LINE (leftX, currentY)-(rightX, currentY), fillCol
        IF currentY > 0 THEN
            scanX = leftX
            DO WHILE scanX <= rightX
                DO WHILE scanX <= rightX AND POINT(scanX, currentY - 1) <> targetCol
                    scanX = scanX + 1
                LOOP
                IF scanX <= rightX THEN
                    stackTop = stackTop + 1
                    stackX(stackTop) = scanX: stackY(stackTop) = currentY - 1
                    DO WHILE scanX <= rightX AND POINT(scanX, currentY - 1) = targetCol
                        scanX = scanX + 1
                    LOOP
                END IF
            LOOP
        END IF
        IF currentY < CANVAS_H - 1 THEN
            scanX = leftX
            DO WHILE scanX <= rightX
                DO WHILE scanX <= rightX AND POINT(scanX, currentY + 1) <> targetCol
                    scanX = scanX + 1
                LOOP
                IF scanX <= rightX THEN
                    stackTop = stackTop + 1
                    stackX(stackTop) = scanX: stackY(stackTop) = currentY + 1
                    DO WHILE scanX <= rightX AND POINT(scanX, currentY + 1) = targetCol
                        scanX = scanX + 1
                    LOOP
                END IF
            LOOP
        END IF
    LOOP
    _DEST 0
END SUB

SUB RenderLayers ()
    DIM targetZ AS INTEGER, i AS INTEGER, maxZ AS INTEGER
    CLS , _RGBA32(0, 0, 0, 0)
    FOR i = 1 TO MAX_LAYER_ID
        IF layerActive(i) AND layerZ(i) > maxZ THEN maxZ = layerZ(i)
    NEXT i
    FOR targetZ = 1 TO maxZ
        FOR i = 1 TO MAX_LAYER_ID
            IF layerActive(i) AND layerVisible(i) AND layerZ(i) = targetZ AND layerImg(i) < -1 THEN _PUTIMAGE (0, 0), layerImg(i), 0
        NEXT i
    NEXT targetZ
END SUB

SUB ReplayHistory ()
    Replay_smiley_1
END SUB

SUB Replay_smiley_1 ()
    IF layerImg(1) < -1 THEN _DEST layerImg(1): CIRCLE ((315 + 510) \ 2, (139 + 323) \ 2), ABS(510 - 315) / 2, _RGB32(0, 0, 0), , , ABS(323 - 139) / ABS(510 - 315): _DEST 0
    CALL FloodFillLikeDRAW (1, 402, 232, _RGB32(255, 255, 85))
    ' Expanded BRUSH seq 5
    IF layerImg(1) < -1 THEN _DEST layerImg(1): _DONTBLEND layerImg(1)
        PSET (392, 202), _RGB32(0, 0, 0)
        _BLEND layerImg(1): _DEST 0
    ' Expanded BRUSH seq 6
    IF layerImg(1) < -1 THEN _DEST layerImg(1): _DONTBLEND layerImg(1)
        PSET (443, 201), _RGB32(0, 0, 0)
        _BLEND layerImg(1): _DEST 0
    IF layerImg(1) < -1 THEN _DEST layerImg(1): LINE (358, 240)-(392, 261), _RGB32(0, 0, 0): _DEST 0
    IF layerImg(1) < -1 THEN _DEST layerImg(1): LINE (392, 261)-(447, 261), _RGB32(0, 0, 0): _DEST 0
    IF layerImg(1) < -1 THEN _DEST layerImg(1): LINE (447, 261)-(476, 239), _RGB32(0, 0, 0): _DEST 0
    IF layerImg(1) < -1 THEN
        _DEST layerImg(1)
        DIM textOldFont8 AS LONG
        DIM textFont8 AS LONG
        textOldFont8 = _FONT
        textFont8 = 0
        COLOR _RGB32(0, 0, 0), _RGBA32(0, 0, 0, 0)
        _PRINTSTRING (351, 174), "smiley SMILEY"
        _FONT textOldFont8
        IF textFont8 > 0 THEN _FREEFONT textFont8
        _DEST 0
    END IF
END SUB

