' DRAW - Generated BAS Export
' Source project generated by DRAW 0.16.0

OPTION _EXPLICIT

CONST CANVAS_W = 864
CONST CANVAS_H = 486

SCREEN _NEWIMAGE(CANVAS_W, CANVAS_H, 32)
CLS , _RGB32(255, 0, 255)
SMILEY
_DISPLAY
DO
    _LIMIT 60
LOOP UNTIL _KEYHIT = 27
SYSTEM

SUB FillPolygonScanline (pointCount AS INTEGER, polyX() AS INTEGER, polyY() AS INTEGER, fillCol AS _UNSIGNED LONG)
    DIM minY AS INTEGER, maxY AS INTEGER
    DIM i AS INTEGER, j AS INTEGER, y AS INTEGER
    DIM nodeCount AS INTEGER, sortIndex AS INTEGER
    DIM nodes() AS SINGLE
    DIM swapValue AS SINGLE
    IF pointCount < 3 THEN EXIT SUB
    minY = polyY(0): maxY = polyY(0)
    FOR i = 1 TO pointCount - 1
        IF polyY(i) < minY THEN minY = polyY(i)
        IF polyY(i) > maxY THEN maxY = polyY(i)
    NEXT i
    REDIM nodes(0 TO pointCount - 1) AS SINGLE
    FOR y = minY TO maxY
        nodeCount = 0
        j = pointCount - 1
        FOR i = 0 TO pointCount - 1
            IF ((polyY(i) < y AND polyY(j) >= y) OR (polyY(j) < y AND polyY(i) >= y)) THEN
                nodes(nodeCount) = polyX(i) + (y - polyY(i)) * (polyX(j) - polyX(i)) / (polyY(j) - polyY(i))
                nodeCount = nodeCount + 1
            END IF
            j = i
        NEXT i
        FOR i = 0 TO nodeCount - 2
            FOR sortIndex = i + 1 TO nodeCount - 1
                IF nodes(sortIndex) < nodes(i) THEN
                    swapValue = nodes(i)
                    nodes(i) = nodes(sortIndex)
                    nodes(sortIndex) = swapValue
                END IF
            NEXT sortIndex
        NEXT i
        FOR i = 0 TO nodeCount - 2 STEP 2
            LINE (INT(nodes(i) + .5), y)-(INT(nodes(i + 1) - .5), y), fillCol
        NEXT i
    NEXT y
END SUB

SUB FillEllipseScanline (x1 AS INTEGER, y1 AS INTEGER, x2 AS INTEGER, y2 AS INTEGER, fillCol AS _UNSIGNED LONG)
    DIM centerX AS SINGLE, centerY AS SINGLE
    DIM radiusX AS SINGLE, radiusY AS SINGLE
    DIM rowOffset AS SINGLE, halfSpan AS SINGLE
    DIM drawY AS INTEGER
    centerX = (x1 + x2) / 2
    centerY = (y1 + y2) / 2
    radiusX = ABS(x2 - x1) / 2
    radiusY = ABS(y2 - y1) / 2
    IF radiusX <= 0 OR radiusY <= 0 THEN EXIT SUB
    FOR drawY = y1 TO y2
        rowOffset = (drawY - centerY) / radiusY
        IF ABS(rowOffset) <= 1 THEN
            halfSpan = radiusX * SQR(1 - rowOffset * rowOffset)
            LINE (INT(centerX - halfSpan + .5), drawY)-(INT(centerX + halfSpan - .5), drawY), fillCol
        END IF
    NEXT drawY
END SUB

SUB SMILEY ()
    ' source kind=ELLIPSE label="Ellipse" export=direct
    CIRCLE ((290 + 368) \ 2, (206 + 284) \ 2), ABS(368 - 290) / 2, _RGB32(0, 0, 0), , , ABS(284 - 206) / ABS(368 - 290)
    ' source kind=FILL label="Fill" export=direct
    CALL FillEllipseScanline(290, 206, 368, 284, _RGB32(255, 255, 85))
    CIRCLE ((290 + 368) \ 2, (206 + 284) \ 2), ABS(368 - 290) / 2, _RGB32(0, 0, 0), , , ABS(284 - 206) / ABS(368 - 290)
    ' source kind=BRUSH label="Dot" export=expanded-raster
    ' begin source kind=BRUSH label="Dot" export=expanded-raster
    _DONTBLEND 0
    PSET (319, 231), _RGB32(0, 0, 0)
    _BLEND 0
    ' end source kind=BRUSH label="Dot" export=expanded-raster
    ' source kind=BRUSH label="Dot" export=expanded-raster
    ' begin source kind=BRUSH label="Dot" export=expanded-raster
    _DONTBLEND 0
    PSET (337, 229), _RGB32(0, 0, 0)
    _BLEND 0
    ' end source kind=BRUSH label="Dot" export=expanded-raster
    ' source kind=POLYLINE label="Polyline" export=direct
    LINE (298, 246)-(309, 257), _RGB32(0, 0, 0)
    LINE (309, 257)-(350, 256), _RGB32(0, 0, 0)
    LINE (350, 256)-(361, 238), _RGB32(0, 0, 0)
    ' source kind=POLYLINE label="Polyline" export=direct
    DIM polyFill7X(0 TO 6) AS INTEGER
    DIM polyFill7Y(0 TO 6) AS INTEGER
    polyFill7X(0) = 330
    polyFill7Y(0) = 257
    polyFill7X(1) = 336
    polyFill7Y(1) = 270
    polyFill7X(2) = 334
    polyFill7Y(2) = 277
    polyFill7X(3) = 341
    polyFill7Y(3) = 280
    polyFill7X(4) = 347
    polyFill7Y(4) = 272
    polyFill7X(5) = 346
    polyFill7Y(5) = 266
    polyFill7X(6) = 339
    polyFill7Y(6) = 257
    CALL FillPolygonScanline(7, polyFill7X(), polyFill7Y(), _RGB32(255, 85, 85))
    LINE (330, 257)-(336, 270), _RGB32(255, 85, 85)
    LINE (336, 270)-(334, 277), _RGB32(255, 85, 85)
    LINE (334, 277)-(341, 280), _RGB32(255, 85, 85)
    LINE (341, 280)-(347, 272), _RGB32(255, 85, 85)
    LINE (347, 272)-(346, 266), _RGB32(255, 85, 85)
    LINE (346, 266)-(339, 257), _RGB32(255, 85, 85)
    LINE (339, 257)-(330, 257), _RGB32(255, 85, 85)
END SUB

