' DRAW - Generated BAS Export
' Source project generated by DRAW 0.16.0

OPTION _EXPLICIT

CONST CANVAS_W = 864
CONST CANVAS_H = 486

SCREEN _NEWIMAGE(CANVAS_W, CANVAS_H, 32)
CLS , _RGBA32(0, 0, 0, 0)
smiley_2
_DISPLAY
SLEEP
SYSTEM

SUB smiley_2 ()
    CIRCLE ((285 + 361) \ 2, (142 + 244) \ 2), ABS(361 - 285) / 2, _RGB32(0, 0, 0), , , ABS(244 - 142) / ABS(361 - 285)
    PAINT (319, 201), _RGB32(255, 255, 85), _RGB32(0, 0, 0)
    _DONTBLEND 0
    PSET (315, 177), _RGB32(0, 0, 0)
    _BLEND 0
    _DONTBLEND 0
    PSET (333, 175), _RGB32(0, 0, 0)
    _BLEND 0
    LINE (306, 198)-(317, 209), _RGB32(0, 0, 0)
    LINE (317, 209)-(341, 210), _RGB32(0, 0, 0)
    LINE (341, 210)-(343, 192), _RGB32(0, 0, 0)
    DIM textOldFont10 AS LONG
    DIM textFont10 AS LONG
    textOldFont10 = _FONT
    textFont10 = 0
    COLOR _RGB32(0, 0, 0), _RGBA32(0, 0, 0, 0)
    _PRINTSTRING (309, 179), "SMILEY"
    _FONT textOldFont10
    IF textFont10 > 0 THEN _FREEFONT textFont10
END SUB

