' DRAW - Generated BAS Export
' Source project generated by DRAW 0.16.0

OPTION _EXPLICIT

CONST CANVAS_W = 864
CONST CANVAS_H = 486

SCREEN _NEWIMAGE(CANVAS_W, CANVAS_H, 32)
CLS , _RGB32(0, 0, 0)
SMILEY
_DISPLAY
_SAVEIMAGE "/home/grymmjack/git/DRAW/DEV/smiley7-generated.png"
SYSTEM

SUB SMILEY ()
    DIM hairX(0 TO 8) AS INTEGER
    DIM hairY(0 TO 8) AS INTEGER
    DIM tongueX(0 TO 5) AS INTEGER
    DIM tongueY(0 TO 5) AS INTEGER

    FillEllipseScanline 320, 117, 447, 244, _RGB32(255, 255, 85)
    CIRCLE ((320 + 447) \ 2, (117 + 244) \ 2), ABS(447 - 320) / 2, _RGB32(0, 0, 0), , , ABS(244 - 117) / ABS(447 - 320)
    _DONTBLEND 0
    PSET (362, 147), _RGB32(0, 0, 0)
    _BLEND 0
    _DONTBLEND 0
    PSET (408, 146), _RGB32(0, 0, 0)
    _BLEND 0
    LINE (327, 176)-(343, 195), _RGB32(0, 0, 0)
    LINE (343, 195)-(424, 195), _RGB32(0, 0, 0)
    LINE (424, 195)-(437, 169), _RGB32(0, 0, 0)
    LINE (325, 155)-(286, 82), _RGB32(0, 0, 0)
    LINE (286, 82)-(327, 116), _RGB32(0, 0, 0)
    LINE (327, 116)-(335, 79), _RGB32(0, 0, 0)
    LINE (335, 79)-(360, 102), _RGB32(0, 0, 0)
    LINE (360, 102)-(461, 57), _RGB32(0, 0, 0)
    LINE (461, 57)-(405, 97), _RGB32(0, 0, 0)
    LINE (405, 97)-(508, 101), _RGB32(0, 0, 0)
    LINE (508, 101)-(454, 119), _RGB32(0, 0, 0)
    LINE (454, 119)-(325, 155), _RGB32(0, 0, 0)
    hairX(0) = 325
    hairY(0) = 155
    hairX(1) = 286
    hairY(1) = 82
    hairX(2) = 327
    hairY(2) = 116
    hairX(3) = 335
    hairY(3) = 79
    hairX(4) = 360
    hairY(4) = 102
    hairX(5) = 461
    hairY(5) = 57
    hairX(6) = 405
    hairY(6) = 97
    hairX(7) = 508
    hairY(7) = 101
    hairX(8) = 454
    hairY(8) = 119
    FillPolygonScanline 9, hairX(), hairY(), _RGB32(170, 85, 0)
    LINE (325, 155)-(286, 82), _RGB32(0, 0, 0)
    LINE (286, 82)-(327, 116), _RGB32(0, 0, 0)
    LINE (327, 116)-(335, 79), _RGB32(0, 0, 0)
    LINE (335, 79)-(360, 102), _RGB32(0, 0, 0)
    LINE (360, 102)-(461, 57), _RGB32(0, 0, 0)
    LINE (461, 57)-(405, 97), _RGB32(0, 0, 0)
    LINE (405, 97)-(508, 101), _RGB32(0, 0, 0)
    LINE (508, 101)-(454, 119), _RGB32(0, 0, 0)
    FillEllipseScanline 320, 117, 447, 244, _RGB32(255, 255, 85)
    CIRCLE ((320 + 447) \ 2, (117 + 244) \ 2), ABS(447 - 320) / 2, _RGB32(0, 0, 0), , , ABS(244 - 117) / ABS(447 - 320)
    _DONTBLEND 0
    PSET (362, 147), _RGB32(0, 0, 0)
    _BLEND 0
    _DONTBLEND 0
    PSET (408, 146), _RGB32(0, 0, 0)
    _BLEND 0
    LINE (327, 176)-(343, 195), _RGB32(0, 0, 0)
    LINE (343, 195)-(424, 195), _RGB32(0, 0, 0)
    LINE (424, 195)-(437, 169), _RGB32(0, 0, 0)
    LINE (384, 196)-(391, 216), _RGB32(170, 85, 0)
    LINE (391, 216)-(387, 232), _RGB32(170, 85, 0)
    LINE (387, 232)-(400, 237), _RGB32(170, 85, 0)
    LINE (400, 237)-(411, 224), _RGB32(170, 85, 0)
    LINE (411, 224)-(403, 196), _RGB32(170, 85, 0)
    LINE (403, 196)-(384, 196), _RGB32(170, 85, 0)
    tongueX(0) = 384
    tongueY(0) = 196
    tongueX(1) = 391
    tongueY(1) = 216
    tongueX(2) = 387
    tongueY(2) = 232
    tongueX(3) = 400
    tongueY(3) = 237
    tongueX(4) = 411
    tongueY(4) = 224
    tongueX(5) = 403
    tongueY(5) = 196
    FillPolygonScanline 6, tongueX(), tongueY(), _RGB32(170, 0, 0)
    LINE (384, 196)-(391, 216), _RGB32(170, 85, 0)
    LINE (391, 216)-(387, 232), _RGB32(170, 85, 0)
    LINE (387, 232)-(400, 237), _RGB32(170, 85, 0)
    LINE (400, 237)-(411, 224), _RGB32(170, 85, 0)
    LINE (411, 224)-(403, 196), _RGB32(170, 85, 0)
    LINE (403, 196)-(384, 196), _RGB32(170, 85, 0)
    _DONTBLEND 0
    LINE (398, 199)-(400, 199), _RGB32(255, 255, 255)
    PSET (394, 200), _RGB32(255, 255, 255)
    LINE (396, 200)-(398, 200), _RGB32(255, 255, 255)
    PSET (400, 201), _RGB32(255, 255, 255)
    LINE (395, 202)-(399, 202), _RGB32(255, 255, 255)
    PSET (401, 202), _RGB32(255, 255, 255)
    LINE (393, 203)-(395, 203), _RGB32(255, 255, 255)
    LINE (397, 203)-(399, 203), _RGB32(255, 255, 255)
    PSET (401, 203), _RGB32(255, 255, 255)
    LINE (393, 204)-(395, 204), _RGB32(255, 255, 255)
    LINE (397, 204)-(398, 204), _RGB32(255, 255, 255)
    LINE (400, 204)-(401, 204), _RGB32(255, 255, 255)
    LINE (393, 205)-(395, 205), _RGB32(255, 255, 255)
    LINE (397, 205)-(398, 205), _RGB32(255, 255, 255)
    PSET (400, 205), _RGB32(255, 255, 255)
    PSET (396, 206), _RGB32(255, 255, 255)
    LINE (399, 206)-(400, 206), _RGB32(255, 255, 255)
    PSET (395, 207), _RGB32(255, 255, 255)
    LINE (397, 207)-(400, 207), _RGB32(255, 255, 255)
    PSET (397, 208), _RGB32(255, 255, 255)
    LINE (399, 208)-(401, 208), _RGB32(255, 255, 255)
    PSET (395, 209), _RGB32(255, 255, 255)
    PSET (400, 209), _RGB32(255, 255, 255)
    PSET (394, 210), _RGB32(255, 255, 255)
    PSET (397, 210), _RGB32(255, 255, 255)
    PSET (399, 210), _RGB32(255, 255, 255)
    PSET (394, 211), _RGB32(255, 255, 255)
    LINE (398, 211)-(399, 211), _RGB32(255, 255, 255)
    LINE (394, 212)-(396, 212), _RGB32(255, 255, 255)
    LINE (398, 212)-(401, 212), _RGB32(255, 255, 255)
    PSET (397, 213), _RGB32(255, 255, 255)
    LINE (401, 213)-(402, 213), _RGB32(255, 255, 255)
    LINE (394, 214)-(395, 214), _RGB32(255, 255, 255)
    PSET (399, 214), _RGB32(255, 255, 255)
    PSET (401, 214), _RGB32(255, 255, 255)
    LINE (398, 215)-(401, 215), _RGB32(255, 255, 255)
    PSET (394, 216), _RGB32(255, 255, 255)
    PSET (396, 216), _RGB32(255, 255, 255)
    PSET (398, 216), _RGB32(255, 255, 255)
    PSET (396, 217), _RGB32(255, 255, 255)
    PSET (399, 217), _RGB32(255, 255, 255)
    PSET (395, 218), _RGB32(255, 255, 255)
    PSET (400, 218), _RGB32(255, 255, 255)
    LINE (395, 219)-(397, 219), _RGB32(255, 255, 255)
    PSET (397, 220), _RGB32(255, 255, 255)
    PSET (401, 220), _RGB32(255, 255, 255)
    PSET (397, 221), _RGB32(255, 255, 255)
    PSET (399, 221), _RGB32(255, 255, 255)
    PSET (395, 222), _RGB32(255, 255, 255)
    PSET (400, 222), _RGB32(255, 255, 255)
    PSET (396, 223), _RGB32(255, 255, 255)
    PSET (398, 223), _RGB32(255, 255, 255)
    LINE (395, 224)-(396, 224), _RGB32(255, 255, 255)
    LINE (398, 224)-(399, 224), _RGB32(255, 255, 255)
    LINE (394, 225)-(395, 225), _RGB32(255, 255, 255)
    PSET (397, 225), _RGB32(255, 255, 255)
    PSET (394, 226), _RGB32(255, 255, 255)
    PSET (398, 226), _RGB32(255, 255, 255)
    PSET (395, 227), _RGB32(255, 255, 255)
    PSET (397, 227), _RGB32(255, 255, 255)
    PSET (400, 227), _RGB32(255, 255, 255)
    PSET (392, 228), _RGB32(255, 255, 255)
    PSET (394, 228), _RGB32(255, 255, 255)
    PSET (391, 229), _RGB32(255, 255, 255)
    PSET (393, 229), _RGB32(255, 255, 255)
    PSET (396, 229), _RGB32(255, 255, 255)
    PSET (398, 229), _RGB32(255, 255, 255)
    PSET (392, 230), _RGB32(255, 255, 255)
    PSET (397, 230), _RGB32(255, 255, 255)
    PSET (392, 231), _RGB32(255, 255, 255)
    PSET (394, 231), _RGB32(255, 255, 255)
    LINE (398, 231)-(399, 231), _RGB32(255, 255, 255)
    PSET (396, 232), _RGB32(255, 255, 255)
    PSET (399, 232), _RGB32(255, 255, 255)
    _BLEND 0
    _DONTBLEND 0
    PSET (357, 133), _RGB32(170, 85, 0)
    PSET (360, 133), _RGB32(170, 85, 0)
    LINE (347, 134)-(350, 134), _RGB32(170, 85, 0)
    LINE (352, 134)-(353, 134), _RGB32(170, 85, 0)
    PSET (356, 134), _RGB32(170, 85, 0)
    PSET (358, 134), _RGB32(170, 85, 0)
    PSET (347, 135), _RGB32(170, 85, 0)
    LINE (351, 135)-(354, 135), _RGB32(170, 85, 0)
    PSET (356, 135), _RGB32(170, 85, 0)
    LINE (359, 135)-(360, 135), _RGB32(170, 85, 0)
    PSET (350, 136), _RGB32(170, 85, 0)
    PSET (354, 136), _RGB32(170, 85, 0)
    PSET (357, 136), _RGB32(170, 85, 0)
    LINE (346, 137)-(347, 137), _RGB32(170, 85, 0)
    PSET (351, 137), _RGB32(170, 85, 0)
    PSET (354, 137), _RGB32(170, 85, 0)
    LINE (359, 137)-(364, 137), _RGB32(170, 85, 0)
    LINE (370, 137)-(371, 137), _RGB32(170, 85, 0)
    LINE (348, 138)-(350, 138), _RGB32(170, 85, 0)
    PSET (352, 138), _RGB32(170, 85, 0)
    PSET (360, 138), _RGB32(170, 85, 0)
    LINE (367, 138)-(368, 138), _RGB32(170, 85, 0)
    LINE (349, 139)-(351, 139), _RGB32(170, 85, 0)
    PSET (357, 139), _RGB32(170, 85, 0)
    PSET (361, 139), _RGB32(170, 85, 0)
    LINE (365, 139)-(366, 139), _RGB32(170, 85, 0)
    PSET (368, 139), _RGB32(170, 85, 0)
    PSET (347, 140), _RGB32(170, 85, 0)
    PSET (349, 140), _RGB32(170, 85, 0)
    LINE (351, 140)-(352, 140), _RGB32(170, 85, 0)
    PSET (354, 140), _RGB32(170, 85, 0)
    LINE (357, 140)-(358, 140), _RGB32(170, 85, 0)
    PSET (360, 140), _RGB32(170, 85, 0)
    PSET (348, 141), _RGB32(170, 85, 0)
    LINE (357, 141)-(358, 141), _RGB32(170, 85, 0)
    LINE (365, 141)-(367, 141), _RGB32(170, 85, 0)
    PSET (366, 142), _RGB32(170, 85, 0)
    PSET (370, 142), _RGB32(170, 85, 0)
    LINE (372, 142)-(373, 142), _RGB32(170, 85, 0)
    PSET (373, 143), _RGB32(170, 85, 0)
    _BLEND 0
    _DONTBLEND 0
    PSET (402, 131), _RGB32(170, 85, 0)
    PSET (408, 131), _RGB32(170, 85, 0)
    PSET (404, 132), _RGB32(170, 85, 0)
    PSET (406, 132), _RGB32(170, 85, 0)
    PSET (408, 132), _RGB32(170, 85, 0)
    PSET (412, 132), _RGB32(170, 85, 0)
    PSET (401, 133), _RGB32(170, 85, 0)
    PSET (403, 133), _RGB32(170, 85, 0)
    LINE (405, 133)-(407, 133), _RGB32(170, 85, 0)
    LINE (409, 133)-(410, 133), _RGB32(170, 85, 0)
    PSET (399, 134), _RGB32(170, 85, 0)
    PSET (402, 134), _RGB32(170, 85, 0)
    PSET (404, 134), _RGB32(170, 85, 0)
    PSET (406, 134), _RGB32(170, 85, 0)
    LINE (409, 134)-(410, 134), _RGB32(170, 85, 0)
    PSET (402, 135), _RGB32(170, 85, 0)
    PSET (404, 135), _RGB32(170, 85, 0)
    LINE (408, 135)-(409, 135), _RGB32(170, 85, 0)
    PSET (412, 135), _RGB32(170, 85, 0)
    LINE (398, 136)-(399, 136), _RGB32(170, 85, 0)
    LINE (404, 136)-(407, 136), _RGB32(170, 85, 0)
    PSET (411, 136), _RGB32(170, 85, 0)
    PSET (402, 137), _RGB32(170, 85, 0)
    PSET (404, 137), _RGB32(170, 85, 0)
    LINE (399, 138)-(400, 138), _RGB32(170, 85, 0)
    LINE (402, 138)-(403, 138), _RGB32(170, 85, 0)
    PSET (406, 138), _RGB32(170, 85, 0)
    PSET (410, 138), _RGB32(170, 85, 0)
    PSET (395, 139), _RGB32(170, 85, 0)
    LINE (400, 139)-(401, 139), _RGB32(170, 85, 0)
    LINE (404, 139)-(405, 139), _RGB32(170, 85, 0)
    PSET (414, 139), _RGB32(170, 85, 0)
    PSET (398, 140), _RGB32(170, 85, 0)
    PSET (402, 140), _RGB32(170, 85, 0)
    LINE (405, 140)-(406, 140), _RGB32(170, 85, 0)
    PSET (394, 141), _RGB32(170, 85, 0)
    LINE (397, 141)-(398, 141), _RGB32(170, 85, 0)
    PSET (396, 142), _RGB32(170, 85, 0)
    PSET (398, 142), _RGB32(170, 85, 0)
    PSET (400, 142), _RGB32(170, 85, 0)
    LINE (399, 143)-(401, 143), _RGB32(170, 85, 0)
    LINE (395, 144)-(396, 144), _RGB32(170, 85, 0)
    PSET (398, 144), _RGB32(170, 85, 0)
    PSET (400, 144), _RGB32(170, 85, 0)
    LINE (399, 145)-(400, 145), _RGB32(170, 85, 0)
    PSET (401, 146), _RGB32(170, 85, 0)
    _BLEND 0
END SUB

SUB FillPolygonScanline (pointCount AS INTEGER, polyX() AS INTEGER, polyY() AS INTEGER, fillCol AS _UNSIGNED LONG)
    DIM minY AS INTEGER, maxY AS INTEGER
    DIM i AS INTEGER, j AS INTEGER, y AS INTEGER
    DIM nodeCount AS INTEGER, sortIndex AS INTEGER
    DIM nodes() AS SINGLE
    DIM swapValue AS SINGLE

    IF pointCount < 3 THEN EXIT SUB
    minY = polyY(0): maxY = polyY(0)
    FOR i = 1 TO pointCount - 1
        IF polyY(i) < minY THEN minY = polyY(i)
        IF polyY(i) > maxY THEN maxY = polyY(i)
    NEXT i
    REDIM nodes(0 TO pointCount - 1) AS SINGLE
    FOR y = minY TO maxY
        nodeCount = 0
        j = pointCount - 1
        FOR i = 0 TO pointCount - 1
            IF ((polyY(i) < y AND polyY(j) >= y) OR (polyY(j) < y AND polyY(i) >= y)) THEN
                nodes(nodeCount) = polyX(i) + (y - polyY(i)) * (polyX(j) - polyX(i)) / (polyY(j) - polyY(i))
                nodeCount = nodeCount + 1
            END IF
            j = i
        NEXT i
        FOR i = 0 TO nodeCount - 2
            FOR sortIndex = i + 1 TO nodeCount - 1
                IF nodes(sortIndex) < nodes(i) THEN
                    swapValue = nodes(i)
                    nodes(i) = nodes(sortIndex)
                    nodes(sortIndex) = swapValue
                END IF
            NEXT sortIndex
        NEXT i
        FOR i = 0 TO nodeCount - 2 STEP 2
            LINE (INT(nodes(i) + .5), y)-(INT(nodes(i + 1) - .5), y), fillCol
        NEXT i
    NEXT y
END SUB

SUB FillEllipseScanline (x1 AS INTEGER, y1 AS INTEGER, x2 AS INTEGER, y2 AS INTEGER, fillCol AS _UNSIGNED LONG)
    DIM centerX AS SINGLE, centerY AS SINGLE
    DIM radiusX AS SINGLE, radiusY AS SINGLE
    DIM rowOffset AS SINGLE, halfSpan AS SINGLE
    DIM drawY AS INTEGER

    centerX = (x1 + x2) / 2
    centerY = (y1 + y2) / 2
    radiusX = ABS(x2 - x1) / 2
    radiusY = ABS(y2 - y1) / 2
    IF radiusX <= 0 OR radiusY <= 0 THEN EXIT SUB
    FOR drawY = y1 TO y2
        rowOffset = (drawY - centerY) / radiusY
        IF ABS(rowOffset) <= 1 THEN
            halfSpan = radiusX * SQR(1 - rowOffset * rowOffset)
            LINE (INT(centerX - halfSpan + .5), drawY)-(INT(centerX + halfSpan - .5), drawY), fillCol
        END IF
    NEXT drawY
END SUB

