' DRAW - Generated BAS History Export
' Source project generated by DRAW 0.16.0
' Canvas: 864x486
' History records: 7 (current cursor=7)
' Supported records in this export: 7
' Unsupported records omitted from executable replay: 0

OPTION _EXPLICIT

TYPE DRAW_HISTORY_EVENT
    kind AS STRING * 16
    sequence AS LONG
    layerId AS LONG
    slotIndex AS INTEGER
    oldZ AS INTEGER
    newZ AS INTEGER
    oldName AS STRING * 64
    newName AS STRING * 64
    label AS STRING * 32
END TYPE

CONST DRAW_HISTORY_EVENT_COUNT = 7
DIM SHARED DRAW_HISTORY(1 TO DRAW_HISTORY_EVENT_COUNT) AS DRAW_HISTORY_EVENT

RESTORE DrawHistoryData
LoadDrawHistory
ShowDrawHistory
END

SUB LoadDrawHistory ()
    DIM i AS INTEGER
    FOR i = 1 TO DRAW_HISTORY_EVENT_COUNT
        READ DRAW_HISTORY(i).kind
        READ DRAW_HISTORY(i).sequence
        READ DRAW_HISTORY(i).layerId
        READ DRAW_HISTORY(i).slotIndex
        READ DRAW_HISTORY(i).oldZ
        READ DRAW_HISTORY(i).newZ
        READ DRAW_HISTORY(i).oldName
        READ DRAW_HISTORY(i).newName
        READ DRAW_HISTORY(i).label
    NEXT i
END SUB

SUB ShowDrawHistory ()
    DIM i AS INTEGER
    PRINT "DRAW history export"
    PRINT "Canvas: 864x486"
    FOR i = 1 TO DRAW_HISTORY_EVENT_COUNT
        PRINT USING "###"; i;
        PRINT "  "; RTRIM$(DRAW_HISTORY(i).kind); " seq="; DRAW_HISTORY(i).sequence; " layer="; DRAW_HISTORY(i).layerId; " slot="; DRAW_HISTORY(i).slotIndex; " oldZ="; DRAW_HISTORY(i).oldZ; " newZ="; DRAW_HISTORY(i).newZ; " label="; RTRIM$(DRAW_HISTORY(i).label)
    NEXT i
END SUB

DrawHistoryData:
DATA "LAYER_ADD",4,2,2,0,2,"Layer 2","","Layer Add"
DATA "LAYER_ADD",5,3,3,0,3,"Layer 3","","Layer Add"
DATA "LAYER_DELETE",7,3,3,3,0,"Layer 3","","Layer Delete"
DATA "LAYER_ADD",8,4,3,0,3,"Layer 2 copy","","Layer Duplicate"
DATA "LAYER_REORDER",10,4,3,3,2,"","","Layer Reorder"
DATA "LAYER_REORDER",11,4,3,2,3,"","","Layer Reorder"
DATA "LAYER_RENAME",12,4,0,0,0,"Layer 2 copy","test","Layer Rename"
