$RESIZE:STRETCH
$CONSOLE

SCREEN _NEWIMAGE(640, 400, 32)
_DELAY 1 ' Let window settle

OPEN "scaled_test.log" FOR OUTPUT AS #1

PRINT #1, "=== QB64-PE Window/Scale Query Test ==="
PRINT #1, "_WIDTH        ="; _WIDTH
PRINT #1, "_HEIGHT       ="; _HEIGHT
PRINT #1, "_SCALEDWIDTH  ="; _SCALEDWIDTH
PRINT #1, "_SCALEDHEIGHT ="; _SCALEDHEIGHT
PRINT #1, "_DESKTOPWIDTH ="; _DESKTOPWIDTH
PRINT #1, "_DESKTOPHEIGHT="; _DESKTOPHEIGHT

CLOSE #1
SYSTEM
